const Discord = require('discord.js')
module.exports = {
    name: 'setup',
    description: "setups the server",
    execute(message, args) {
        const type = args[0];
        const ServerSetup = new Discord.MessageEmbed()
            .setTitle('Server Setup')
            .setDescription('auto!setup [Types]')
            .addField('The are 2 types of servers', 'basic, support')
            .setColor('RED')
            .setFooter('Auto Server!')
        const NotOwner = new Discord.MessageEmbed()
            .setTitle('Owner?')
            .setDescription('I think **NOT**')
            .addField('Only the owner of the server can use this command!', 'Contact your server owner!')
            .setColor('RED')
            .setFooter('Auto Server!')
        if (message.author === !message.guild.owner) return message.channel.send(NotOwner)
        if (!type) return message.channel.send(ServerSetup)
        if (type === 'basic') {
            message.guild.channels.cache.forEach(channel => channel.delete());
            message.guild.channels.create('Text Channels', { type: 'category' })
            message.guild.channels.create('💬General', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🌐International', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🤖bot commands', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🎫self promotion', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🤣Memes', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('❓Other', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('Voice Channels', { type: 'category' })
            message.guild.channels.create('General VC | #1', { type: 'voice' })
            message.guild.channels.create('General VC | #2', { type: 'voice' })
            message.guild.channels.create('General VC | #3', { type: 'voice' })
            message.guild.channels.create('Stream VC | #1', { type: 'voice' })
            message.guild.channels.create('Stream VC | #2', { type: 'voice' })
            message.guild.channels.create('Stream VC | #3', { type: 'voice' })
            const InstuctionEmbed = new Discord.MessageEmbed()
                .setTitle(`Intructions for ${message.guild.name}`)
                .setDescription('Channels have been created')
                .addField('Server Result Appears Below', 'Happy Server Making')
                .setColor('#a8dadc')
                .setFooter('Auto Server')
                .setTimestamp()
            message.author.send(InstuctionEmbed)
            message.author.send({ files: ["./images/basic_setup.png"] })
        } else if (type === 'support') {
            message.guild.channels.cache.forEach(channel => channel.delete());
            message.guild.channels.create('Text Channels', { type: 'category' })
            message.guild.channels.create('💬General', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🌐International', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🤖bot commands', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🎫self promotion', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🤣Memes', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('❓Other', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('Voice Channels', { type: 'category' })
            message.guild.channels.create('General VC | #1', { type: 'voice' })
            message.guild.channels.create('General VC | #2', { type: 'voice' })
            message.guild.channels.create('General VC | #3', { type: 'voice' })
            message.guild.channels.create('Stream VC | #1', { type: 'voice' })
            message.guild.channels.create('Stream VC | #2', { type: 'voice' })
            message.guild.channels.create('Stream VC | #3', { type: 'voice' })
            message.guild.channels.create('Support', { type: 'category' })
            message.guild.channels.create('💭support 1', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('💭support 2', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('🤔suggestions', { reason: 'Needed a cool new channel' })
            message.guild.channels.create('Support VC | #1', { type: 'voice' })
            message.guild.channels.create('Support VC | #2', { type: 'voice' })
            message.guild.channels.create('Support VC | #3', { type: 'voice' })
            const InstuctionEmbed = new Discord.MessageEmbed()
                .setTitle(`Intructions for ${message.guild.name}`)
                .setDescription('Channels have been created')
                .addField('Server Result Appears Below', 'Happy Server Making')
                .addField('Note:', 'Make sure the support vc are in its category')
                .setColor('#a8dadc')
                .setFooter('Auto Server')
                .setTimestamp()
            message.author.send(InstuctionEmbed)
            message.author.send({ files: ["./images/support_setup.png"] })
        }
    }
}